package com.zuicoding.platform.blog.dao;

import com.zuicoding.platform.blog.modal.WpCommentmeta;

import java.util.List;

public interface WpCommentmetaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_commentmeta
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_commentmeta
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    int insert(WpCommentmeta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_commentmeta
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    WpCommentmeta selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_commentmeta
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    List<WpCommentmeta> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_commentmeta
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    int updateByPrimaryKey(WpCommentmeta record);
}