package com.zuicoding.platform.blog.dao;

import com.zuicoding.platform.blog.base.Pager;
import com.zuicoding.platform.blog.modal.WpComment;
import com.zuicoding.platform.blog.modal.WpCommentKey;
import com.zuicoding.platform.blog.modal.WpCommentWithBLOBs;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface WpCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_comment
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    int deleteByPrimaryKey(WpCommentKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_comment
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    int insert(WpCommentWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_comment
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    int insertSelective(WpCommentWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_comment
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    WpCommentWithBLOBs selectByPrimaryKey(WpCommentKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_comment
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    int updateByPrimaryKeySelective(WpCommentWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_comment
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(WpCommentWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_comment
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    int updateByPrimaryKey(WpComment record);

    /**
     *  某个用户的评论总数
     * @param userId
     * @return
     */
    int selectCountByUserId(int userId);

    /**
     *  某个用户待评论的总数
     * @param userId
     * @return
     */
    int selectAppCountByUserId(int userId);

    /**
     * 分页查询 某个文章的评论
     * @param pager
     * @param postId
     * @return
     */
    List<WpCommentWithBLOBs> selectWithPager(@Param("pager")Pager pager,
                                             @Param("userId")Integer userId,
                                             @Param("postId")Integer postId);
}