package com.zuicoding.platform.blog.dao;

import com.zuicoding.platform.blog.modal.WpCommentmeta;
import com.zuicoding.platform.blog.modal.WpCommentmetaKey;
import com.zuicoding.platform.blog.modal.WpCommentmetaWithBLOBs;

public interface WpCommentmetaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_commentmeta
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    int deleteByPrimaryKey(WpCommentmetaKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_commentmeta
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    int insert(WpCommentmetaWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_commentmeta
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    int insertSelective(WpCommentmetaWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_commentmeta
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    WpCommentmetaWithBLOBs selectByPrimaryKey(WpCommentmetaKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_commentmeta
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    int updateByPrimaryKeySelective(WpCommentmetaWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_commentmeta
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(WpCommentmetaWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_commentmeta
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    int updateByPrimaryKey(WpCommentmeta record);
}