package com.zuicoding.platform.blog.dao;

import com.zuicoding.platform.blog.modal.WpComment;

import java.util.List;

public interface WpCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_comment
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_comment
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    int insert(WpComment record);



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_comment
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    List<WpComment> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_comment
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    int updateByPrimaryKey(WpComment record);
}