package com.zuicoding.platform.blog.dao;

import com.zuicoding.platform.blog.modal.WpLink;


import java.util.List;

public interface WpLinkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_link
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_link
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    int insert(WpLink record);



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_link
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    List<WpLink> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_link
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    int updateByPrimaryKey(WpLink record);
}