package com.zuicoding.platform.blog.dao;

import com.zuicoding.platform.blog.modal.WpLink;
import com.zuicoding.platform.blog.modal.WpLinkKey;
import com.zuicoding.platform.blog.modal.WpLinkWithBLOBs;

public interface WpLinkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_link
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    int deleteByPrimaryKey(WpLinkKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_link
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    int insert(WpLinkWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_link
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    int insertSelective(WpLinkWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_link
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    WpLinkWithBLOBs selectByPrimaryKey(WpLinkKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_link
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    int updateByPrimaryKeySelective(WpLinkWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_link
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(WpLinkWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_link
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    int updateByPrimaryKey(WpLink record);
}