package com.zuicoding.platform.blog.dao;

import com.zuicoding.platform.blog.modal.WpMenu;

import java.util.List;

public interface WpMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_menu
     *
     * @mbg.generated Mon Jul 24 18:04:55 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_menu
     *
     * @mbg.generated Mon Jul 24 18:04:55 CST 2017
     */
    int insert(WpMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_menu
     *
     * @mbg.generated Mon Jul 24 18:04:55 CST 2017
     */
    WpMenu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_menu
     *
     * @mbg.generated Mon Jul 24 18:04:55 CST 2017
     */
    List<WpMenu> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_menu
     *
     * @mbg.generated Mon Jul 24 18:04:55 CST 2017
     */
    int updateByPrimaryKey(WpMenu record);
}