package com.zuicoding.platform.blog.dao;

import com.zuicoding.platform.blog.modal.WpOption;
import com.zuicoding.platform.blog.modal.WpOptionKey;
import com.zuicoding.platform.blog.modal.WpOptionWithBLOBs;

public interface WpOptionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_option
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    int deleteByPrimaryKey(WpOptionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_option
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    int insert(WpOptionWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_option
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    int insertSelective(WpOptionWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_option
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    WpOptionWithBLOBs selectByPrimaryKey(WpOptionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_option
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    int updateByPrimaryKeySelective(WpOptionWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_option
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(WpOptionWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_option
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    int updateByPrimaryKey(WpOption record);
}