package com.zuicoding.platform.blog.dao;

import com.zuicoding.platform.blog.modal.WpOption;

import java.util.List;

public interface WpOptionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_option
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_option
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    int insert(WpOption record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_option
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    List<WpOption> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_option
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    int updateByPrimaryKey(WpOption record);
}