package com.zuicoding.platform.blog.dao;

import com.zuicoding.platform.blog.modal.WpPostmeta;
import com.zuicoding.platform.blog.modal.WpPostmetaKey;
import com.zuicoding.platform.blog.modal.WpPostmetaWithBLOBs;

public interface WpPostmetaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_postmeta
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    int deleteByPrimaryKey(WpPostmetaKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_postmeta
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    int insert(WpPostmetaWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_postmeta
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    int insertSelective(WpPostmetaWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_postmeta
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    WpPostmetaWithBLOBs selectByPrimaryKey(WpPostmetaKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_postmeta
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    int updateByPrimaryKeySelective(WpPostmetaWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_postmeta
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(WpPostmetaWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_postmeta
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    int updateByPrimaryKey(WpPostmeta record);
}