package com.zuicoding.platform.blog.dao;

import com.zuicoding.platform.blog.modal.WpPost;

import java.util.List;

public interface WpPostMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_post
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_post
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    int insert(WpPost record);



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_post
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    List<WpPost> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_post
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    int updateByPrimaryKey(WpPost record);
}