package com.zuicoding.platform.blog.dao;

import com.zuicoding.platform.blog.modal.WpTerm;

import java.util.List;

public interface WpTermMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_term
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_term
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    int insert(WpTerm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_term
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    WpTerm selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_term
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    List<WpTerm> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_term
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    int updateByPrimaryKey(WpTerm record);
}