package com.zuicoding.platform.blog.dao;

import com.zuicoding.platform.blog.modal.WpTermmeta;
import com.zuicoding.platform.blog.modal.WpTermmetaKey;
import com.zuicoding.platform.blog.modal.WpTermmetaWithBLOBs;

public interface WpTermmetaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_termmeta
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    int deleteByPrimaryKey(WpTermmetaKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_termmeta
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    int insert(WpTermmetaWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_termmeta
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    int insertSelective(WpTermmetaWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_termmeta
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    WpTermmetaWithBLOBs selectByPrimaryKey(WpTermmetaKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_termmeta
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    int updateByPrimaryKeySelective(WpTermmetaWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_termmeta
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(WpTermmetaWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_termmeta
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    int updateByPrimaryKey(WpTermmeta record);
}