package com.zuicoding.platform.blog.dao;

import com.zuicoding.platform.blog.modal.WpTermTaxonomy;
import java.util.List;

public interface WpTermTaxonomyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_term_taxonomy
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_term_taxonomy
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    int insert(WpTermTaxonomy record);



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_term_taxonomy
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    List<WpTermTaxonomy> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_term_taxonomy
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    int updateByPrimaryKey(WpTermTaxonomy record);
}