package com.zuicoding.platform.blog.dao;

import com.zuicoding.platform.blog.modal.WpTermRelationship;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface WpTermRelationshipMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_term_relationship
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    int deleteByPrimaryKey(@Param("objectId") Long objectId, @Param("termTaxonomyId") Long termTaxonomyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_term_relationship
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    int insert(WpTermRelationship record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_term_relationship
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    WpTermRelationship selectByPrimaryKey(@Param("objectId") Long objectId, @Param("termTaxonomyId") Long termTaxonomyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_term_relationship
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    List<WpTermRelationship> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_term_relationship
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    int updateByPrimaryKey(WpTermRelationship record);
}