package com.zuicoding.platform.blog.dao;

import com.zuicoding.platform.blog.modal.WpTermTaxonomy;
import com.zuicoding.platform.blog.modal.WpTermTaxonomyKey;
import com.zuicoding.platform.blog.modal.WpTermTaxonomyWithBLOBs;

public interface WpTermTaxonomyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_term_taxonomy
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    int deleteByPrimaryKey(WpTermTaxonomyKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_term_taxonomy
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    int insert(WpTermTaxonomyWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_term_taxonomy
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    int insertSelective(WpTermTaxonomyWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_term_taxonomy
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    WpTermTaxonomyWithBLOBs selectByPrimaryKey(WpTermTaxonomyKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_term_taxonomy
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    int updateByPrimaryKeySelective(WpTermTaxonomyWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_term_taxonomy
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(WpTermTaxonomyWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_term_taxonomy
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    int updateByPrimaryKey(WpTermTaxonomy record);
}