package com.zuicoding.platform.blog.dao;

import com.zuicoding.platform.blog.modal.WpTermRelationship;
import com.zuicoding.platform.blog.modal.WpTermRelationshipKey;

public interface WpTermRelationshipMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_term_relationship
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    int deleteByPrimaryKey(WpTermRelationshipKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_term_relationship
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    int insert(WpTermRelationship record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_term_relationship
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    int insertSelective(WpTermRelationship record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_term_relationship
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    WpTermRelationship selectByPrimaryKey(WpTermRelationshipKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_term_relationship
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    int updateByPrimaryKeySelective(WpTermRelationship record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_term_relationship
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    int updateByPrimaryKey(WpTermRelationship record);
}