package com.zuicoding.platform.blog.dao;

import com.zuicoding.platform.blog.modal.WpUser;

import java.util.List;

public interface WpUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_user
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_user
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    int insert(WpUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_user
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    WpUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_user
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    List<WpUser> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_user
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    int updateByPrimaryKey(WpUser record);
}