package com.zuicoding.platform.blog.dao;

import com.zuicoding.platform.blog.modal.WpUsermeta;

import java.util.List;

public interface WpUsermetaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_usermeta
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_usermeta
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    int insert(WpUsermeta record);



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_usermeta
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    List<WpUsermeta> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_usermeta
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    int updateByPrimaryKey(WpUsermeta record);
}