package com.zuicoding.platform.blog.dao;

import com.zuicoding.platform.blog.modal.WpUsermeta;
import com.zuicoding.platform.blog.modal.WpUsermetaKey;
import com.zuicoding.platform.blog.modal.WpUsermetaWithBLOBs;

public interface WpUsermetaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_usermeta
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    int deleteByPrimaryKey(WpUsermetaKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_usermeta
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    int insert(WpUsermetaWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_usermeta
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    int insertSelective(WpUsermetaWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_usermeta
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    WpUsermetaWithBLOBs selectByPrimaryKey(WpUsermetaKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_usermeta
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    int updateByPrimaryKeySelective(WpUsermetaWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_usermeta
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(WpUsermetaWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_usermeta
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    int updateByPrimaryKey(WpUsermeta record);
}