package com.zuicoding.platform.blog.modal;

public class WpCommentWithBLOBs extends WpComment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_comment.comment_content
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    private String commentContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_comment.comment_content
     *
     * @return the value of wp_comment.comment_content
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    public String getCommentContent() {
        return commentContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_comment.comment_content
     *
     * @param commentContent the value for wp_comment.comment_content
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    public void setCommentContent(String commentContent) {
        this.commentContent = commentContent == null ? null : commentContent.trim();
    }
}