package com.zuicoding.platform.blog.modal;

public class WpCommentmeta extends WpCommentmetaKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_commentmeta.comment_id
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    private Long commentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_commentmeta.meta_key
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    private String metaKey;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_commentmeta.comment_id
     *
     * @return the value of wp_commentmeta.comment_id
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    public Long getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_commentmeta.comment_id
     *
     * @param commentId the value for wp_commentmeta.comment_id
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    public void setCommentId(Long commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_commentmeta.meta_key
     *
     * @return the value of wp_commentmeta.meta_key
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    public String getMetaKey() {
        return metaKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_commentmeta.meta_key
     *
     * @param metaKey the value for wp_commentmeta.meta_key
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    public void setMetaKey(String metaKey) {
        this.metaKey = metaKey == null ? null : metaKey.trim();
    }
}