package com.zuicoding.platform.blog.modal;

import java.util.Date;

public class WpComment extends WpCommentKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_comment.comment_post_id
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    private Long commentPostId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_comment.comment_author
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    private String commentAuthor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_comment.comment_author_email
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    private String commentAuthorEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_comment.comment_author_url
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    private String commentAuthorUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_comment.comment_author_IP
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    private String commentAuthorIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_comment.comment_date
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    private Date commentDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_comment.comment_date_gmt
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    private Date commentDateGmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_comment.comment_karma
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    private Integer commentKarma;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_comment.comment_approved
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    private String commentApproved;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_comment.comment_agent
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    private String commentAgent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_comment.comment_type
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    private String commentType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_comment.comment_parent
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    private Long commentParent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_comment.user_id
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    private Long userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_comment.comment_post_id
     *
     * @return the value of wp_comment.comment_post_id
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    public Long getCommentPostId() {
        return commentPostId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_comment.comment_post_id
     *
     * @param commentPostId the value for wp_comment.comment_post_id
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    public void setCommentPostId(Long commentPostId) {
        this.commentPostId = commentPostId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_comment.comment_author
     *
     * @return the value of wp_comment.comment_author
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    public String getCommentAuthor() {
        return commentAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_comment.comment_author
     *
     * @param commentAuthor the value for wp_comment.comment_author
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    public void setCommentAuthor(String commentAuthor) {
        this.commentAuthor = commentAuthor == null ? null : commentAuthor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_comment.comment_author_email
     *
     * @return the value of wp_comment.comment_author_email
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    public String getCommentAuthorEmail() {
        return commentAuthorEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_comment.comment_author_email
     *
     * @param commentAuthorEmail the value for wp_comment.comment_author_email
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    public void setCommentAuthorEmail(String commentAuthorEmail) {
        this.commentAuthorEmail = commentAuthorEmail == null ? null : commentAuthorEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_comment.comment_author_url
     *
     * @return the value of wp_comment.comment_author_url
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    public String getCommentAuthorUrl() {
        return commentAuthorUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_comment.comment_author_url
     *
     * @param commentAuthorUrl the value for wp_comment.comment_author_url
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    public void setCommentAuthorUrl(String commentAuthorUrl) {
        this.commentAuthorUrl = commentAuthorUrl == null ? null : commentAuthorUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_comment.comment_author_IP
     *
     * @return the value of wp_comment.comment_author_IP
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    public String getCommentAuthorIp() {
        return commentAuthorIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_comment.comment_author_IP
     *
     * @param commentAuthorIp the value for wp_comment.comment_author_IP
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    public void setCommentAuthorIp(String commentAuthorIp) {
        this.commentAuthorIp = commentAuthorIp == null ? null : commentAuthorIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_comment.comment_date
     *
     * @return the value of wp_comment.comment_date
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    public Date getCommentDate() {
        return commentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_comment.comment_date
     *
     * @param commentDate the value for wp_comment.comment_date
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    public void setCommentDate(Date commentDate) {
        this.commentDate = commentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_comment.comment_date_gmt
     *
     * @return the value of wp_comment.comment_date_gmt
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    public Date getCommentDateGmt() {
        return commentDateGmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_comment.comment_date_gmt
     *
     * @param commentDateGmt the value for wp_comment.comment_date_gmt
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    public void setCommentDateGmt(Date commentDateGmt) {
        this.commentDateGmt = commentDateGmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_comment.comment_karma
     *
     * @return the value of wp_comment.comment_karma
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    public Integer getCommentKarma() {
        return commentKarma;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_comment.comment_karma
     *
     * @param commentKarma the value for wp_comment.comment_karma
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    public void setCommentKarma(Integer commentKarma) {
        this.commentKarma = commentKarma;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_comment.comment_approved
     *
     * @return the value of wp_comment.comment_approved
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    public String getCommentApproved() {
        return commentApproved;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_comment.comment_approved
     *
     * @param commentApproved the value for wp_comment.comment_approved
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    public void setCommentApproved(String commentApproved) {
        this.commentApproved = commentApproved == null ? null : commentApproved.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_comment.comment_agent
     *
     * @return the value of wp_comment.comment_agent
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    public String getCommentAgent() {
        return commentAgent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_comment.comment_agent
     *
     * @param commentAgent the value for wp_comment.comment_agent
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    public void setCommentAgent(String commentAgent) {
        this.commentAgent = commentAgent == null ? null : commentAgent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_comment.comment_type
     *
     * @return the value of wp_comment.comment_type
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    public String getCommentType() {
        return commentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_comment.comment_type
     *
     * @param commentType the value for wp_comment.comment_type
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    public void setCommentType(String commentType) {
        this.commentType = commentType == null ? null : commentType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_comment.comment_parent
     *
     * @return the value of wp_comment.comment_parent
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    public Long getCommentParent() {
        return commentParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_comment.comment_parent
     *
     * @param commentParent the value for wp_comment.comment_parent
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    public void setCommentParent(Long commentParent) {
        this.commentParent = commentParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_comment.user_id
     *
     * @return the value of wp_comment.user_id
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_comment.user_id
     *
     * @param userId the value for wp_comment.user_id
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }
}