package com.zuicoding.platform.blog.modal;

import java.util.Date;

public class WpLink {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_link.id
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_link.url
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_link.name
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_link.img
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    private String img;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_link.target
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    private String target;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_link.description
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_link.visible
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    private String visible;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_link.owner
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    private Long owner;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_link.rating
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    private Integer rating;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_link.updated
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    private Date updated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_link.rel
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    private String rel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_link.rss
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    private String rss;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_link.notes
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    private String notes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_link.id
     *
     * @return the value of wp_link.id
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_link.id
     *
     * @param id the value for wp_link.id
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_link.url
     *
     * @return the value of wp_link.url
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_link.url
     *
     * @param url the value for wp_link.url
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_link.name
     *
     * @return the value of wp_link.name
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_link.name
     *
     * @param name the value for wp_link.name
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_link.img
     *
     * @return the value of wp_link.img
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_link.img
     *
     * @param img the value for wp_link.img
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_link.target
     *
     * @return the value of wp_link.target
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    public String getTarget() {
        return target;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_link.target
     *
     * @param target the value for wp_link.target
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    public void setTarget(String target) {
        this.target = target == null ? null : target.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_link.description
     *
     * @return the value of wp_link.description
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_link.description
     *
     * @param description the value for wp_link.description
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_link.visible
     *
     * @return the value of wp_link.visible
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    public String getVisible() {
        return visible;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_link.visible
     *
     * @param visible the value for wp_link.visible
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    public void setVisible(String visible) {
        this.visible = visible == null ? null : visible.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_link.owner
     *
     * @return the value of wp_link.owner
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    public Long getOwner() {
        return owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_link.owner
     *
     * @param owner the value for wp_link.owner
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    public void setOwner(Long owner) {
        this.owner = owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_link.rating
     *
     * @return the value of wp_link.rating
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    public Integer getRating() {
        return rating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_link.rating
     *
     * @param rating the value for wp_link.rating
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    public void setRating(Integer rating) {
        this.rating = rating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_link.updated
     *
     * @return the value of wp_link.updated
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    public Date getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_link.updated
     *
     * @param updated the value for wp_link.updated
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_link.rel
     *
     * @return the value of wp_link.rel
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    public String getRel() {
        return rel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_link.rel
     *
     * @param rel the value for wp_link.rel
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    public void setRel(String rel) {
        this.rel = rel == null ? null : rel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_link.rss
     *
     * @return the value of wp_link.rss
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    public String getRss() {
        return rss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_link.rss
     *
     * @param rss the value for wp_link.rss
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    public void setRss(String rss) {
        this.rss = rss == null ? null : rss.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_link.notes
     *
     * @return the value of wp_link.notes
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    public String getNotes() {
        return notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_link.notes
     *
     * @param notes the value for wp_link.notes
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    public void setNotes(String notes) {
        this.notes = notes == null ? null : notes.trim();
    }
}