package com.zuicoding.platform.blog.modal;

import java.util.Date;

public class WpLink extends WpLinkKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_link.link_url
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    private String linkUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_link.link_name
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    private String linkName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_link.link_image
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    private String linkImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_link.link_target
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    private String linkTarget;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_link.link_description
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    private String linkDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_link.link_visible
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    private String linkVisible;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_link.link_owner
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    private Long linkOwner;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_link.link_rating
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    private Integer linkRating;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_link.link_updated
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    private Date linkUpdated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_link.link_rel
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    private String linkRel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_link.link_rss
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    private String linkRss;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_link.link_url
     *
     * @return the value of wp_link.link_url
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    public String getLinkUrl() {
        return linkUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_link.link_url
     *
     * @param linkUrl the value for wp_link.link_url
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    public void setLinkUrl(String linkUrl) {
        this.linkUrl = linkUrl == null ? null : linkUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_link.link_name
     *
     * @return the value of wp_link.link_name
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    public String getLinkName() {
        return linkName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_link.link_name
     *
     * @param linkName the value for wp_link.link_name
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    public void setLinkName(String linkName) {
        this.linkName = linkName == null ? null : linkName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_link.link_image
     *
     * @return the value of wp_link.link_image
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    public String getLinkImage() {
        return linkImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_link.link_image
     *
     * @param linkImage the value for wp_link.link_image
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    public void setLinkImage(String linkImage) {
        this.linkImage = linkImage == null ? null : linkImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_link.link_target
     *
     * @return the value of wp_link.link_target
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    public String getLinkTarget() {
        return linkTarget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_link.link_target
     *
     * @param linkTarget the value for wp_link.link_target
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    public void setLinkTarget(String linkTarget) {
        this.linkTarget = linkTarget == null ? null : linkTarget.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_link.link_description
     *
     * @return the value of wp_link.link_description
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    public String getLinkDescription() {
        return linkDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_link.link_description
     *
     * @param linkDescription the value for wp_link.link_description
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    public void setLinkDescription(String linkDescription) {
        this.linkDescription = linkDescription == null ? null : linkDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_link.link_visible
     *
     * @return the value of wp_link.link_visible
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    public String getLinkVisible() {
        return linkVisible;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_link.link_visible
     *
     * @param linkVisible the value for wp_link.link_visible
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    public void setLinkVisible(String linkVisible) {
        this.linkVisible = linkVisible == null ? null : linkVisible.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_link.link_owner
     *
     * @return the value of wp_link.link_owner
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    public Long getLinkOwner() {
        return linkOwner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_link.link_owner
     *
     * @param linkOwner the value for wp_link.link_owner
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    public void setLinkOwner(Long linkOwner) {
        this.linkOwner = linkOwner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_link.link_rating
     *
     * @return the value of wp_link.link_rating
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    public Integer getLinkRating() {
        return linkRating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_link.link_rating
     *
     * @param linkRating the value for wp_link.link_rating
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    public void setLinkRating(Integer linkRating) {
        this.linkRating = linkRating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_link.link_updated
     *
     * @return the value of wp_link.link_updated
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    public Date getLinkUpdated() {
        return linkUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_link.link_updated
     *
     * @param linkUpdated the value for wp_link.link_updated
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    public void setLinkUpdated(Date linkUpdated) {
        this.linkUpdated = linkUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_link.link_rel
     *
     * @return the value of wp_link.link_rel
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    public String getLinkRel() {
        return linkRel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_link.link_rel
     *
     * @param linkRel the value for wp_link.link_rel
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    public void setLinkRel(String linkRel) {
        this.linkRel = linkRel == null ? null : linkRel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_link.link_rss
     *
     * @return the value of wp_link.link_rss
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    public String getLinkRss() {
        return linkRss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_link.link_rss
     *
     * @param linkRss the value for wp_link.link_rss
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    public void setLinkRss(String linkRss) {
        this.linkRss = linkRss == null ? null : linkRss.trim();
    }
}