package com.zuicoding.platform.blog.modal;

public class WpLinkWithBLOBs extends WpLink {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_link.link_notes
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    private String linkNotes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_link.link_notes
     *
     * @return the value of wp_link.link_notes
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    public String getLinkNotes() {
        return linkNotes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_link.link_notes
     *
     * @param linkNotes the value for wp_link.link_notes
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    public void setLinkNotes(String linkNotes) {
        this.linkNotes = linkNotes == null ? null : linkNotes.trim();
    }
}