package com.zuicoding.platform.blog.modal;

public class WpMenu {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_menu.id
     *
     * @mbg.generated Mon Jul 24 18:04:55 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_menu.name
     *
     * @mbg.generated Mon Jul 24 18:04:55 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_menu.src
     *
     * @mbg.generated Mon Jul 24 18:04:55 CST 2017
     */
    private String src;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_menu.parent_id
     *
     * @mbg.generated Mon Jul 24 18:04:55 CST 2017
     */
    private Integer parentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_menu.id
     *
     * @return the value of wp_menu.id
     *
     * @mbg.generated Mon Jul 24 18:04:55 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_menu.id
     *
     * @param id the value for wp_menu.id
     *
     * @mbg.generated Mon Jul 24 18:04:55 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_menu.name
     *
     * @return the value of wp_menu.name
     *
     * @mbg.generated Mon Jul 24 18:04:55 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_menu.name
     *
     * @param name the value for wp_menu.name
     *
     * @mbg.generated Mon Jul 24 18:04:55 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_menu.src
     *
     * @return the value of wp_menu.src
     *
     * @mbg.generated Mon Jul 24 18:04:55 CST 2017
     */
    public String getSrc() {
        return src;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_menu.src
     *
     * @param src the value for wp_menu.src
     *
     * @mbg.generated Mon Jul 24 18:04:55 CST 2017
     */
    public void setSrc(String src) {
        this.src = src == null ? null : src.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_menu.parent_id
     *
     * @return the value of wp_menu.parent_id
     *
     * @mbg.generated Mon Jul 24 18:04:55 CST 2017
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_menu.parent_id
     *
     * @param parentId the value for wp_menu.parent_id
     *
     * @mbg.generated Mon Jul 24 18:04:55 CST 2017
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }
}