package com.zuicoding.platform.blog.modal;

public class WpOption {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_option.id
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_option.blog_id
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    private Long blogId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_option.option_name
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    private String optionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_option.autoload
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    private String autoload;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_option.option_value
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    private String optionValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_option.id
     *
     * @return the value of wp_option.id
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_option.id
     *
     * @param id the value for wp_option.id
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_option.blog_id
     *
     * @return the value of wp_option.blog_id
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    public Long getBlogId() {
        return blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_option.blog_id
     *
     * @param blogId the value for wp_option.blog_id
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    public void setBlogId(Long blogId) {
        this.blogId = blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_option.option_name
     *
     * @return the value of wp_option.option_name
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    public String getOptionName() {
        return optionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_option.option_name
     *
     * @param optionName the value for wp_option.option_name
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    public void setOptionName(String optionName) {
        this.optionName = optionName == null ? null : optionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_option.autoload
     *
     * @return the value of wp_option.autoload
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    public String getAutoload() {
        return autoload;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_option.autoload
     *
     * @param autoload the value for wp_option.autoload
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    public void setAutoload(String autoload) {
        this.autoload = autoload == null ? null : autoload.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_option.option_value
     *
     * @return the value of wp_option.option_value
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    public String getOptionValue() {
        return optionValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_option.option_value
     *
     * @param optionValue the value for wp_option.option_value
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    public void setOptionValue(String optionValue) {
        this.optionValue = optionValue == null ? null : optionValue.trim();
    }
}