package com.zuicoding.platform.blog.modal;

public class WpOption extends WpOptionKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_option.option_name
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    private String optionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_option.autoload
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    private String autoload;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_option.option_name
     *
     * @return the value of wp_option.option_name
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    public String getOptionName() {
        return optionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_option.option_name
     *
     * @param optionName the value for wp_option.option_name
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    public void setOptionName(String optionName) {
        this.optionName = optionName == null ? null : optionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_option.autoload
     *
     * @return the value of wp_option.autoload
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    public String getAutoload() {
        return autoload;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_option.autoload
     *
     * @param autoload the value for wp_option.autoload
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    public void setAutoload(String autoload) {
        this.autoload = autoload == null ? null : autoload.trim();
    }
}