package com.zuicoding.platform.blog.modal;

public class WpOptionWithBLOBs extends WpOption {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_option.option_value
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    private String optionValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_option.option_value
     *
     * @return the value of wp_option.option_value
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    public String getOptionValue() {
        return optionValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_option.option_value
     *
     * @param optionValue the value for wp_option.option_value
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    public void setOptionValue(String optionValue) {
        this.optionValue = optionValue == null ? null : optionValue.trim();
    }
}