package com.zuicoding.platform.blog.modal;

public class WpPostmeta {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_postmeta.id
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_postmeta.post_id
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    private Long postId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_postmeta.meta_key
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    private String metaKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_postmeta.meta_value
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    private String metaValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_postmeta.id
     *
     * @return the value of wp_postmeta.id
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_postmeta.id
     *
     * @param id the value for wp_postmeta.id
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_postmeta.post_id
     *
     * @return the value of wp_postmeta.post_id
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    public Long getPostId() {
        return postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_postmeta.post_id
     *
     * @param postId the value for wp_postmeta.post_id
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    public void setPostId(Long postId) {
        this.postId = postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_postmeta.meta_key
     *
     * @return the value of wp_postmeta.meta_key
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    public String getMetaKey() {
        return metaKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_postmeta.meta_key
     *
     * @param metaKey the value for wp_postmeta.meta_key
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    public void setMetaKey(String metaKey) {
        this.metaKey = metaKey == null ? null : metaKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_postmeta.meta_value
     *
     * @return the value of wp_postmeta.meta_value
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    public String getMetaValue() {
        return metaValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_postmeta.meta_value
     *
     * @param metaValue the value for wp_postmeta.meta_value
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    public void setMetaValue(String metaValue) {
        this.metaValue = metaValue == null ? null : metaValue.trim();
    }
}