package com.zuicoding.platform.blog.modal;

public class WpPostmeta extends WpPostmetaKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_postmeta.post_id
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    private Long postId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_postmeta.meta_key
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    private String metaKey;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_postmeta.post_id
     *
     * @return the value of wp_postmeta.post_id
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    public Long getPostId() {
        return postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_postmeta.post_id
     *
     * @param postId the value for wp_postmeta.post_id
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    public void setPostId(Long postId) {
        this.postId = postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_postmeta.meta_key
     *
     * @return the value of wp_postmeta.meta_key
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    public String getMetaKey() {
        return metaKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_postmeta.meta_key
     *
     * @param metaKey the value for wp_postmeta.meta_key
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    public void setMetaKey(String metaKey) {
        this.metaKey = metaKey == null ? null : metaKey.trim();
    }
}