package com.zuicoding.platform.blog.modal;

public class WpTermRelationship {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_term_relationship.object_id
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    private Long objectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_term_relationship.term_taxonomy_id
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    private Long termTaxonomyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_term_relationship.term_order
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    private Integer termOrder;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_term_relationship.object_id
     *
     * @return the value of wp_term_relationship.object_id
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    public Long getObjectId() {
        return objectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_term_relationship.object_id
     *
     * @param objectId the value for wp_term_relationship.object_id
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    public void setObjectId(Long objectId) {
        this.objectId = objectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_term_relationship.term_taxonomy_id
     *
     * @return the value of wp_term_relationship.term_taxonomy_id
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    public Long getTermTaxonomyId() {
        return termTaxonomyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_term_relationship.term_taxonomy_id
     *
     * @param termTaxonomyId the value for wp_term_relationship.term_taxonomy_id
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    public void setTermTaxonomyId(Long termTaxonomyId) {
        this.termTaxonomyId = termTaxonomyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_term_relationship.term_order
     *
     * @return the value of wp_term_relationship.term_order
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    public Integer getTermOrder() {
        return termOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_term_relationship.term_order
     *
     * @param termOrder the value for wp_term_relationship.term_order
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    public void setTermOrder(Integer termOrder) {
        this.termOrder = termOrder;
    }
}