package com.zuicoding.platform.blog.modal;

public class WpTermmeta extends WpTermmetaKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_termmeta.term_id
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    private Long termId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_termmeta.meta_key
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    private String metaKey;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_termmeta.term_id
     *
     * @return the value of wp_termmeta.term_id
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    public Long getTermId() {
        return termId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_termmeta.term_id
     *
     * @param termId the value for wp_termmeta.term_id
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    public void setTermId(Long termId) {
        this.termId = termId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_termmeta.meta_key
     *
     * @return the value of wp_termmeta.meta_key
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    public String getMetaKey() {
        return metaKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_termmeta.meta_key
     *
     * @param metaKey the value for wp_termmeta.meta_key
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    public void setMetaKey(String metaKey) {
        this.metaKey = metaKey == null ? null : metaKey.trim();
    }
}