package com.zuicoding.platform.blog.modal;

public class WpTermRelationship extends WpTermRelationshipKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_term_relationship.term_order
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    private Integer termOrder;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_term_relationship.term_order
     *
     * @return the value of wp_term_relationship.term_order
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    public Integer getTermOrder() {
        return termOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_term_relationship.term_order
     *
     * @param termOrder the value for wp_term_relationship.term_order
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    public void setTermOrder(Integer termOrder) {
        this.termOrder = termOrder;
    }
}