package com.zuicoding.platform.blog.modal;

public class WpTermRelationshipKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_term_relationship.id
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    private Long objectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_term_relationship.term_taxonomy_id
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    private Long termTaxonomyId;

    public Long getObjectId() {
        return objectId;
    }

    public void setObjectId(Long objectId) {
        this.objectId = objectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_term_relationship.term_taxonomy_id
     *
     * @return the value of wp_term_relationship.term_taxonomy_id
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    public Long getTermTaxonomyId() {
        return termTaxonomyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_term_relationship.term_taxonomy_id
     *
     * @param termTaxonomyId the value for wp_term_relationship.term_taxonomy_id
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    public void setTermTaxonomyId(Long termTaxonomyId) {
        this.termTaxonomyId = termTaxonomyId;
    }
}