package com.zuicoding.platform.blog.modal;

public class WpTermTaxonomy extends WpTermTaxonomyKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_term_taxonomy.term_id
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    private Long termId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_term_taxonomy.taxonomy
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    private String taxonomy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_term_taxonomy.parent
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    private Long parent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_term_taxonomy.count
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    private Long count;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_term_taxonomy.term_id
     *
     * @return the value of wp_term_taxonomy.term_id
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    public Long getTermId() {
        return termId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_term_taxonomy.term_id
     *
     * @param termId the value for wp_term_taxonomy.term_id
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    public void setTermId(Long termId) {
        this.termId = termId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_term_taxonomy.taxonomy
     *
     * @return the value of wp_term_taxonomy.taxonomy
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    public String getTaxonomy() {
        return taxonomy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_term_taxonomy.taxonomy
     *
     * @param taxonomy the value for wp_term_taxonomy.taxonomy
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    public void setTaxonomy(String taxonomy) {
        this.taxonomy = taxonomy == null ? null : taxonomy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_term_taxonomy.parent
     *
     * @return the value of wp_term_taxonomy.parent
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    public Long getParent() {
        return parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_term_taxonomy.parent
     *
     * @param parent the value for wp_term_taxonomy.parent
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    public void setParent(Long parent) {
        this.parent = parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_term_taxonomy.count
     *
     * @return the value of wp_term_taxonomy.count
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    public Long getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_term_taxonomy.count
     *
     * @param count the value for wp_term_taxonomy.count
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    public void setCount(Long count) {
        this.count = count;
    }
}