package com.zuicoding.platform.blog.modal;

public class WpTermTaxonomyWithBLOBs extends WpTermTaxonomy {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_term_taxonomy.description
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_term_taxonomy.description
     *
     * @return the value of wp_term_taxonomy.description
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_term_taxonomy.description
     *
     * @param description the value for wp_term_taxonomy.description
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}