package com.zuicoding.platform.blog.modal;

public class WpTerm extends WpTermKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_term.name
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_term.slug
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    private String slug;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_term.term_group
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    private Long termGroup;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_term.name
     *
     * @return the value of wp_term.name
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_term.name
     *
     * @param name the value for wp_term.name
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_term.slug
     *
     * @return the value of wp_term.slug
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    public String getSlug() {
        return slug;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_term.slug
     *
     * @param slug the value for wp_term.slug
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    public void setSlug(String slug) {
        this.slug = slug == null ? null : slug.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_term.term_group
     *
     * @return the value of wp_term.term_group
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    public Long getTermGroup() {
        return termGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_term.term_group
     *
     * @param termGroup the value for wp_term.term_group
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    public void setTermGroup(Long termGroup) {
        this.termGroup = termGroup;
    }
}