package com.zuicoding.platform.blog.modal;

public class WpUsermeta {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_usermeta.id
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_usermeta.user_id
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_usermeta.meta_key
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    private String metaKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_usermeta.meta_value
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    private String metaValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_usermeta.id
     *
     * @return the value of wp_usermeta.id
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_usermeta.id
     *
     * @param id the value for wp_usermeta.id
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_usermeta.user_id
     *
     * @return the value of wp_usermeta.user_id
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_usermeta.user_id
     *
     * @param userId the value for wp_usermeta.user_id
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_usermeta.meta_key
     *
     * @return the value of wp_usermeta.meta_key
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    public String getMetaKey() {
        return metaKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_usermeta.meta_key
     *
     * @param metaKey the value for wp_usermeta.meta_key
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    public void setMetaKey(String metaKey) {
        this.metaKey = metaKey == null ? null : metaKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_usermeta.meta_value
     *
     * @return the value of wp_usermeta.meta_value
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    public String getMetaValue() {
        return metaValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_usermeta.meta_value
     *
     * @param metaValue the value for wp_usermeta.meta_value
     *
     * @mbg.generated Fri Jul 14 15:17:38 CST 2017
     */
    public void setMetaValue(String metaValue) {
        this.metaValue = metaValue == null ? null : metaValue.trim();
    }
}