package com.zuicoding.platform.blog.modal;

public class WpUsermeta extends WpUsermetaKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_usermeta.user_id
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_usermeta.meta_key
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    private String metaKey;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_usermeta.user_id
     *
     * @return the value of wp_usermeta.user_id
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_usermeta.user_id
     *
     * @param userId the value for wp_usermeta.user_id
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_usermeta.meta_key
     *
     * @return the value of wp_usermeta.meta_key
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    public String getMetaKey() {
        return metaKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_usermeta.meta_key
     *
     * @param metaKey the value for wp_usermeta.meta_key
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    public void setMetaKey(String metaKey) {
        this.metaKey = metaKey == null ? null : metaKey.trim();
    }
}