package com.zuicoding.platform.blog.modal;

public class WpUsersKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_users.id
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    private Long id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_users.id
     *
     * @return the value of wp_users.id
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_users.id
     *
     * @param id the value for wp_users.id
     *
     * @mbg.generated Fri Aug 04 11:24:08 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }
}